DROP TABLE IF EXISTS `fakturabanktransaction`;
CREATE TABLE `fakturabanktransaction` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `FakturabankID` bigint(20) NOT NULL,
  `Incoming` tinyint(1) DEFAULT NULL,
  `Amount` decimal(16,5) DEFAULT NULL,
  `Currency` varchar(4) DEFAULT NULL,
  `Description` varchar(255) DEFAULT NULL,
  `DoneReconciliatedAt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `FromBankAccount` varchar(255) DEFAULT NULL,                                                         
  `ToBankAccount` varchar(255) DEFAULT NULL,                                                         
  `PostingDate` date NOT NULL DEFAULT '0000-00-00 00:00:00',
  `Ref` varchar(255) DEFAULT NULL,                                                         
  `KID` varchar(255) DEFAULT NULL,                                                         
  `TransactionBatchId` bigint(20) NOT NULL,
  `UnitId` bigint(20) NOT NULL,
  `CreatedAt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `CreatedBy` varchar(255) DEFAULT NULL,                                                         
  `UpdatedAt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `FakturabankID` (`FakturabankID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `fakturabanktransactionrelation`;
CREATE TABLE `fakturabanktransactionrelation` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,                                                                 
  `FakturabankID` bigint(20) NOT NULL,
  `FakturabankTransactionID` bigint(20) NOT NULL,
  `FakturabankInvoiceID` bigint(20) DEFAULT NULL,
  `InvoiceID` bigint(20) DEFAULT NULL,
  `AccountPlanID` bigint(20) DEFAULT NULL,
  `AccountPlanOrgNumber` bigint(20) DEFAULT NULL,
  `Incoming` tinyint(1) DEFAULT NULL,
  `Description` varchar(255) DEFAULT NULL,
  `DoneReconciliatedAt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `FromBankAccount` varchar(255) DEFAULT NULL,                                                         
  `ToBankAccount` varchar(255) DEFAULT NULL,                                                         
  `PostingDate` date NOT NULL DEFAULT '0000-00-00 00:00:00',
  `Ref` varchar(255) DEFAULT NULL,                                                         
  `KID` varchar(255) DEFAULT NULL,                                                         
  `Type` varchar(63) DEFAULT NULL,
  `Amount` decimal(16,5) DEFAULT NULL,
  `Currency` varchar(4) DEFAULT NULL,
  `FakturabankBankTransactionAccountID` bigint(20) NOT NULL,
  `CreatedAt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `CreatedByID` bigint(20) NOT NULL,
  `UpdatedAt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `UpdatedByID` bigint(20) NOT NULL,
  `AccountID` bigint(20) NOT NULL,
  `AccountType` varchar(255) DEFAULT NULL,
  `AccountName` varchar(255) DEFAULT NULL,
  `AccountClose` tinyint(1) DEFAULT NULL,
  `AccountCreatedAt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `AccountUpdatedAt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `FakturabankID` (`FakturabankID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `fakturabankinvoicein`;
CREATE TABLE `fakturabankinvoicein` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,                                                                 
  `FakturabankID` bigint(20) NOT NULL,
  `LodoID` bigint(20) NOT NULL,
  `FakturabankNumber` varchar(255) DEFAULT NULL,
  `ProfileID` varchar(255) DEFAULT NULL,
  `KID` varchar(30) DEFAULT NULL,                                                                          
  `IssueDate` date NOT NULL DEFAULT '0000-00-00',                                                            
  `DocumentCurrency` varchar(4) DEFAULT NULL,
  `SupplierPartyIndentification` varchar(255) DEFAULT NULL,
  `SupplierPartyIndentificationSchemeID` varchar(255) DEFAULT NULL,
  `SupplierPartyName` varchar(255) DEFAULT NULL,
  `CustomerPartyIndentification` varchar(255) DEFAULT NULL,
  `CustomerPartyIndentificationSchemeID` varchar(255) DEFAULT NULL,
  `CustomerPartyName` varchar(255) DEFAULT NULL,
  `PaymentMeansCode` varchar(10) DEFAULT NULL,
  `PaymentMeansDueDate` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `TaxTotalAmount` decimal(16,5) DEFAULT NULL,
  `TaxTotalAmountCurrency` varchar(4) DEFAULT NULL,
  `LegalMonetaryTotTaxExclusAmount` decimal(16,5) DEFAULT NULL,
  `LegalMonetaryTotTaxExclusAmountCurrency` varchar(4) DEFAULT NULL,
  `LegalMonetaryTotPayableAmount` decimal(16,5) DEFAULT NULL,
  `LegalMonetaryTotPayableAmountCurrency` varchar(4) DEFAULT NULL,
  `Class` varchar(255) DEFAULT NULL,
  `Status` varchar(511) DEFAULT NULL,
  `Journal` varchar(10) DEFAULT NULL,
  `JournalID` varchar(10) DEFAULT NULL,
  `AccountPlanID` bigint(20) DEFAULT NULL,
  `AccountPlanOrgNumber` bigint(20) DEFAULT NULL,
  `VoucherType` varchar(4) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `FakturabankID` (`FakturabankID`)                             
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

