INSERT
  INTO currency
	(CurrencyISO, CurrencyName)
  VALUES 
	('AFN','Afghani'),
	('DZD','Algerian Dinar'),
	('ARS','Argentine Peso'),
	('AWG','Aruban Guilder'),
	('AUD','Australian Dollar'),
	('AZM','Azerbaijanian Manat'),
	('BSD','Bahamian Dollar'),
	('BHD','Bahraini Dinar'),
	('THB','Baht'),
	('PAB','Balboa'),
	('BBD','Barbados Dollar'),
	('BYR','Belarussian Ruble'),
	('BZD','Belize Dollar'),
	('BMD','Bermudian Dollar'),
	('VEB','Bolivar'),
	('BOB','Boliviano'),
	('BRL','Brazilian Real'),
	('BND','Brunei Dollar'),
	('BGN','Bulgarian Lev'),
	('BIF','Burundi Franc'),
	('CAD','Canadian Dollar'),
	('CVE','Cape Verde Escudo'),
	('KYD','Cayman Islands Dollar'),
	('GHC','Cedi'),
	('XAF','CFA Franc'),
	('XPF','CFP Franc'),
	('CLP','Chilean Peso'),
	('COP','Colombian Peso'),
	('KMF','Comoro Franc'),
	('BAM','Convertible Mark'),
	('NIO','Cordoba Oro'),
	('CRC','Costa Rican Colon'),
	('CUP','Cuban Peso'),
	('CYP','Cyprus Pound'),
	('CZK','Czech Koruna'),
	('GMD','Dalasi'),
	('DKK','Danish Krone'),
	('MKD','Denar'),
	('AED','Dirham'),
	('DJF','Djibouti Franc'),
	('STD','Dobra'),
	('DOP','Dominican Peso'),
	('VND','Dong'),
	('AMD','Dram'),
	('XCD','East Carribean Dollar'),
	('EGP','Egyptian Pound'),
	('SVC','El Salvador Colon'),
	('ETB','Ethopian Birr'),
	('EUR','Euro'),
	('FKP','Falkland Islands Pound'),
	('FJD','Fiji Dollar'),
	('HUF','Forint'),
	('CDF','Franc Congolais'),
	('GIP','Gibraltar Pound'),
	('XAU','Gold'),
	('HTG','Gourde'),
	('PYG','Guarani'),
	('GNF','Guinea Franc'),
	('GYD','Guyana Dollar'),
	('HKD','Honk Kong Dollar'),
	('UAH','Hryvnia'),
	('ISK','Iceland Krona'),
	('INR','Indian Rupee'),
	('IRR','Iranian Rial'),
	('IQD','Iraqi Dinar'),
	('JMD','Jamaican Dollar'),
	('JOD','Jordanian Dinar'),
	('KES','Kenyan Shilling'),
	('PGK','Kina'),
	('LAK','Kip'),
	('EEK','Kroon'),
	('HRK','Kuna'),
	('KWD','Kuwaiti Dinar'),
	('MWK','Kwacha'),
	('ZMK','Kwacha'),
	('AOA','Kwanza'),
	('MMK','Kyat'),
	('GEL','Lari'),
	('LVL','Latvian Lats'),
	('LBP','Lebanese Pound'),
	('ALL','Lek'),
	('HNL','Lempira'),
	('SLL','Leone'),
	('ROL','Leu'),
	('LRD','Liberian Dollar'),
	('LYD','Libyan Dinar'),
	('SZL','Lilangeni'),
	('LTL','Lithuanian Litas'),
	('LSL','Loti'),
	('MGF','Malagasy Franc'),
	('MYR','Malaysian Ringgit'),
	('MTL','Maltese Lira'),
	('TMM','Manat'),
	('MUR','Mauritius Rupee'),
	('MZM','Metical'),
	('MXN','Mexican Peso'),
	('MDL','Moldovan Leu'),
	('MAD','Morrocan Dirham'),
	('NGN','Naira'),
	('ERN','Nakfa'),
	('NAD','Namibia Dollar'),
	('NPR','Nepalese Rupee'),
	('ANG','Netherlands Antillian Guilder'),
	('YUM','New Dinar'),
	('ILS','New Israeli Sheqel'),
	('TWD','New Taiwan Dollar'),
	('NZD','New Zealand Dollar'),
	('BTN','Ngultrum'),
	('KPW','North Korean Won'),
	('NOK','Norwegian Krone'),
	('PEN','Nuevo Sol'),
	('MRO','Ouguiya'),
	('TOP','Pa''anga'),
	('PKR','Pakistan Rupee'),
	('XPD','Palladium'),
	('MOP','Pataca'),
	('UYU','Peso Uruguayo'),
	('PHP','Philippine Peso'),
	('XPT','Platinum'),
	('GBP','Pound Sterling'),
	('BWP','Pula'),
	('QAR','Qatari Rial'),
	('GTQ','Quetzal'),
	('ZAR','Rand'),
	('OMR','Rial Omani'),
	('KHR','Riel'),
	('MVR','Rufiyaa'),
	('IDR','Rupiah'),
	('RUB','Russian Ruble'),
	('RWF','Rwanda Franc'),
	('SAR','Saudi Riyal'),
	('XDR','SDR'),
	('SCR','Seychelles Rupee'),
	('XAG','Silver'),
	('SGD','Singapore Dollar'),
	('SKK','Slovak Koruna'),
	('SBD','Solomon Islands Dollar'),
	('KGS','Som'),
	('SOS','Somali Shilling'),
	('TJS','Somoni'),
	('LKR','Sri Lanka Rupee'),
	('SHP','St. Helena Pound'),
	('SDD','Sudanese Dinar'),
	('SRG','Suriname Guilder'),
	('SEK','Swedish Krona'),
	('CHF','Swiss Franc'),
	('SYP','Syrian Pound'),
	('BDT','Taka'),
	('WST','Tala'),
	('TZS','Tanzanian Shilling'),
	('KZT','Tenge'),
	('SIT','Tolar'),
	('TTD','Trinidad and Tobago Dollar'),
	('MNT','Tugrik'),
	('TND','Tunisian Dinar'),
	('TRL','Turkish Lira'),
	('UGX','Uganda Shilling'),
	('USD','US Dollar'),
	('UZS','Uzbekistan Sum'),
	('VUV','Vatu'),
	('KRW','Won'),
	('YER','Yemeni Rial'),
	('JPY','Yen'),
	('CNY','Yuan Renminbi'),
	('ZWD','Zimbabwe Dollar'),
	('PLN','Zloty')
	;