DROP TABLE IF EXISTS `fakturabankinvoiceout`;
CREATE TABLE `fakturabankinvoiceout` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,                                                                 
  `FakturabankID` bigint(20) NOT NULL,
  `LodoID` bigint(20) NOT NULL,
  `FakturabankNumber` varchar(255) DEFAULT NULL,
  `ProfileID` varchar(255) DEFAULT NULL,
  `KID` varchar(30) DEFAULT NULL,                                                                          
  `IssueDate` date NOT NULL DEFAULT '0000-00-00',                                                            
  `DocumentCurrency` varchar(4) DEFAULT NULL,
  `SupplierPartyIndentification` varchar(255) DEFAULT NULL,
  `SupplierPartyIndentificationSchemeID` varchar(255) DEFAULT NULL,
  `SupplierPartyName` varchar(255) DEFAULT NULL,
  `CustomerPartyIndentification` varchar(255) DEFAULT NULL,
  `CustomerPartyIndentificationSchemeID` varchar(255) DEFAULT NULL,
  `CustomerPartyName` varchar(255) DEFAULT NULL,
  `PaymentMeansCode` varchar(10) DEFAULT NULL,
  `PaymentMeansDueDate` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `TaxTotalAmount` decimal(16,5) DEFAULT NULL,
  `TaxTotalAmountCurrency` varchar(4) DEFAULT NULL,
  `LegalMonetaryTotTaxExclusAmount` decimal(16,5) DEFAULT NULL,
  `LegalMonetaryTotTaxExclusAmountCurrency` varchar(4) DEFAULT NULL,
  `LegalMonetaryTotPayableAmount` decimal(16,5) DEFAULT NULL,
  `LegalMonetaryTotPayableAmountCurrency` varchar(4) DEFAULT NULL,
  `Class` varchar(255) DEFAULT NULL,
  `Status` varchar(511) DEFAULT NULL,
  `Journal` varchar(10) DEFAULT NULL,
  `JournalID` varchar(10) DEFAULT NULL,
  `AccountPlanID` bigint(20) DEFAULT NULL,
  `AccountPlanOrgNumber` bigint(20) DEFAULT NULL,
  `VoucherType` varchar(4) DEFAULT NULL,
  `TransactionAmount` decimal(16,5) DEFAULT NULL,
  `TransactionCurrency` varchar(4) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `FakturabankID` (`FakturabankID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;