
 CREATE  TABLE  `accountplantemplate` (  `AccountPlanID` bigint( 20  )  NOT  NULL DEFAULT  '0',
 `AccountName` varchar( 255  )  DEFAULT NULL ,
 `FirstName` varchar( 50  )  DEFAULT NULL ,
 `LastName` varchar( 50  )  DEFAULT NULL ,
 `VatID` int( 11  )  DEFAULT NULL ,
 `Report` varchar( 255  )  DEFAULT NULL ,
 `Budget` double  DEFAULT NULL ,
 `TS` timestamp NOT  NULL  DEFAULT CURRENT_TIMESTAMP  ON  UPDATE  CURRENT_TIMESTAMP ,
 `InsertedDateTime` datetime  DEFAULT NULL ,
 `InsertedByPersonID` int( 11  )  DEFAULT NULL ,
 `ValidFrom` datetime  DEFAULT NULL ,
 `ValidTo` datetime  DEFAULT NULL ,
 `debittext` varchar( 20  )  DEFAULT NULL ,
 `credittext` varchar( 20  )  DEFAULT NULL ,
 `Currency` char( 3  )  DEFAULT NULL ,
 `Description` text,
 `EnableReskontro` smallint( 6  ) DEFAULT  '0',
 `EnableQuantity` smallint( 6  )  DEFAULT NULL ,
 `EnableDepartment` smallint( 6  )  DEFAULT NULL ,
 `EnableProject` smallint( 6  )  DEFAULT NULL ,
 `EnableReport1` smallint( 6  )  DEFAULT NULL ,
 `EnableReport2` smallint( 6  )  DEFAULT NULL ,
 `EnableReport3` smallint( 6  )  DEFAULT NULL ,
 `EnableReport4` smallint( 6  )  DEFAULT NULL ,
 `EnableReport5` smallint( 6  )  DEFAULT NULL ,
 `EnableReport6` smallint( 6  )  DEFAULT NULL ,
 `EnableReport7` smallint( 6  )  DEFAULT NULL ,
 `EnableReport8` smallint( 6  )  DEFAULT NULL ,
 `EnableReport9` smallint( 6  )  DEFAULT NULL ,
 `EnableReport10` smallint( 6  )  DEFAULT NULL ,
 `EnableReportShort` smallint( 6  )  DEFAULT NULL ,
 `EnableBudgetResult` smallint( 6  )  DEFAULT NULL ,
 `EnableBudgetLikviditet` smallint( 6  )  DEFAULT NULL ,
 `Report1Line` varchar( 10  ) DEFAULT  '0',
 `Report2Line` varchar( 10  ) DEFAULT  '0',
 `Report3Line` varchar( 10  ) DEFAULT  '0',
 `Report4Line` varchar( 10  ) DEFAULT  '0',
 `Report5Line` varchar( 10  ) DEFAULT  '0',
 `Report6Line` varchar( 10  ) DEFAULT  '0',
 `Report7Line` varchar( 10  ) DEFAULT  '0',
 `Report8Line` varchar( 10  ) DEFAULT  '0',
 `Report9Line` varchar( 10  ) DEFAULT  '0',
 `Report10Line` varchar( 10  ) DEFAULT  '0',
 `ReportShort` int( 11  )  DEFAULT NULL ,
 `EnableVATOverride` smallint( 6  )  DEFAULT NULL ,
 `EnablePostPost` smallint( 6  )  DEFAULT NULL ,
 `ReskontroFromAccount` bigint( 20  )  DEFAULT NULL ,
 `ReskontroToAccount` bigint( 20  )  DEFAULT NULL ,
 `EnableZeroYearly` int( 11  )  DEFAULT NULL ,
 `Reskontro` int( 11  )  DEFAULT NULL ,
 `EnableVAT` smallint( 6  )  DEFAULT NULL ,
 `Address` varchar( 255  )  DEFAULT NULL ,
 `ZipCode` varchar( 10  )  DEFAULT NULL ,
 `Email` varchar( 255  )  DEFAULT NULL ,
 `DomesticBankAccount` varchar( 255  )  DEFAULT NULL ,
 `AbroadBankAccount` varchar( 20  )  DEFAULT NULL ,
 `EnableSalary` smallint( 6  )  DEFAULT NULL ,
 `SocialSecurityNumber` int( 11  )  DEFAULT NULL ,
 `Municipality` varchar( 255  )  DEFAULT NULL ,
 `EmployedFromDate` date  DEFAULT NULL ,
 `EmployedToDate` date  DEFAULT NULL ,
 `SalaryDue` float  DEFAULT NULL ,
 `EnableCredit` smallint( 6  )  DEFAULT NULL ,
 `CreditDays` int( 11  )  DEFAULT NULL ,
 `EnableAutogiro` smallint( 6  )  DEFAULT NULL ,
 `EnableNettbank` smallint( 6  )  DEFAULT NULL ,
 `DebitColor` varchar( 10  )  DEFAULT NULL ,
 `CreditColor` varchar( 10  )  DEFAULT NULL ,
 `Active` smallint( 6  ) DEFAULT  '1',
 `EnableCurrency` smallint( 6  )  DEFAULT NULL ,
 `CustomerNumber` varchar( 10  )  DEFAULT NULL ,
 `EnableMotkontoBalanse` smallint( 6  )  DEFAULT NULL ,
 `MotkontoBalanse1` bigint( 20  )  DEFAULT NULL ,
 `MotkontoBalanse2` bigint( 20  )  DEFAULT NULL ,
 `MotkontoBalanse3` bigint( 20  )  DEFAULT NULL ,
 `MotkontoResultat1` bigint( 20  )  DEFAULT NULL ,
 `MotkontoResultat2` bigint( 20  )  DEFAULT NULL ,
 `MotkontoResultat3` bigint( 20  )  DEFAULT NULL ,
 `EnableMotkontoResultat` smallint( 6  )  DEFAULT NULL ,
 `LastUsedTime` datetime  DEFAULT NULL ,
 `City` varchar( 50  )  DEFAULT NULL ,
 `EnablePersonalUsage` smallint( 6  )  DEFAULT NULL ,
 `EnableMoneyFlow` smallint( 6  )  DEFAULT NULL ,
 `EnableSaldo` smallint( 6  )  DEFAULT NULL ,
 `NorwegianStandardText` varchar( 255  )  DEFAULT NULL ,
 `OrgNumber` varchar( 20  )  DEFAULT NULL ,
 `VatNumber` varchar( 255  )  DEFAULT NULL ,
 `SocietyNumber` varchar( 15  )  DEFAULT NULL ,
 `KommuneID` int( 11  )  DEFAULT NULL ,
 `WorkStart` date  DEFAULT NULL ,
 `WorkStop` date  DEFAULT NULL ,
 `EnableNorwegianStandard` smallint( 6  )  DEFAULT NULL ,
 `PersonID` int( 11  )  DEFAULT NULL ,
 `ProjectID` int( 11  ) DEFAULT  '0',
 `DepartmentID` int( 11  ) DEFAULT  '0',
 `TabellTrekk` varchar( 10  )  DEFAULT NULL ,
 `ProsentTrekk` varchar( 10  )  DEFAULT NULL ,
 `Phone` varchar( 20  )  DEFAULT NULL ,
 `IPoBox` varchar( 255  )  DEFAULT NULL ,
 `IPoBoxCity` varchar( 255  )  DEFAULT NULL ,
 `Mobile` varchar( 255  )  DEFAULT NULL ,
 `EnableInvoicePoBox` smallint( 6  )  DEFAULT NULL ,
 `EnableInvoiceAddress` smallint( 6  )  DEFAULT NULL ,
 `IPoBoxZipCode` varchar( 255  )  DEFAULT NULL ,
 `BirthDate` datetime  DEFAULT NULL ,
 `WorkPercent` decimal( 16, 2  )  DEFAULT NULL ,
 `EnableSalaryPayment` smallint( 6  )  DEFAULT NULL ,
 `Report1LinePage` varchar( 5  )  NOT  NULL DEFAULT  '',
 `Report2LinePage` varchar( 5  )  NOT  NULL DEFAULT  '',
 `Report3LinePage` varchar( 5  )  NOT  NULL DEFAULT  '',
 `Report4LinePage` varchar( 5  )  NOT  NULL DEFAULT  '',
 `Report5LinePage` varchar( 5  )  NOT  NULL DEFAULT  '',
 `Report6LinePage` varchar( 5  )  NOT  NULL DEFAULT  '',
 `Report7LinePage` varchar( 5  )  NOT  NULL DEFAULT  '',
 `Report8LinePage` varchar( 5  )  NOT  NULL DEFAULT  '',
 `Report9LinePage` varchar( 5  )  NOT  NULL DEFAULT  '',
 `Report10LinePage` varchar( 5  )  NOT  NULL DEFAULT  '',
 `IPoBoxZipCodeCity` varchar( 255  )  DEFAULT NULL ,
 `Report66Line` varchar( 11  )  DEFAULT NULL ,
 `Report0002Line` varchar( 11  )  DEFAULT NULL ,
 `Report1224Line` varchar( 11  )  DEFAULT NULL ,
 `Report2224Line` varchar( 11  )  DEFAULT NULL ,
 `Report1028Line` varchar( 11  )  DEFAULT NULL ,
 `Report1125Line` varchar( 11  )  DEFAULT NULL ,
 `Report1217Line` varchar( 11  )  DEFAULT NULL ,
 `Report1122Line` varchar( 11  )  DEFAULT NULL ,
 `Report1052Line` varchar( 11  )  DEFAULT NULL ,
 `Report1223Line` varchar( 11  )  DEFAULT NULL ,
 `Report1219Line` varchar( 11  )  DEFAULT NULL ,
 `Report1061Line` varchar( 11  )  DEFAULT NULL ,
 `Report1239Line` varchar( 11  )  DEFAULT NULL ,
 `Report1215Line` varchar( 11  )  DEFAULT NULL ,
 `Report1221Line` varchar( 11  )  DEFAULT NULL ,
 `Report1037Line` varchar( 11  )  DEFAULT NULL ,
 `Report1025Line` varchar( 11  )  DEFAULT NULL ,
 `Report1231Line` varchar( 11  )  DEFAULT NULL ,
 `Report1022Line` varchar( 11  )  DEFAULT NULL ,
 `Report1086Line` varchar( 11  )  DEFAULT NULL ,
 `EnableReport1224` smallint( 6  )  DEFAULT NULL ,
 `EnableReport2224` smallint( 6  )  DEFAULT NULL ,
 `InvoiceCommentCustomerPosition` varchar( 10  )  NOT  NULL DEFAULT  'bottom',
 `ReskontroAccountPlanType` varchar( 15  )  DEFAULT NULL ,
 `AccountPlanType` varchar( 9  )  DEFAULT NULL ,
 `UpdatedByPersonID` int( 11  )  DEFAULT NULL ,
 `AccountLineFreeTextMatch` varchar( 255  )  DEFAULT NULL ,
 `CountryCode` varchar( 2  )  NOT  NULL DEFAULT  'NO',
 `isAccountCustomer` smallint( 6  )  DEFAULT NULL ,
 `isAccountSupplier` smallint( 6  )  DEFAULT NULL ,
 `isAccountResult` smallint( 6  )  DEFAULT NULL ,
 `isAccountBalance` smallint( 6  )  DEFAULT NULL ,
 `isAccountEmployee` smallint( 6  )  DEFAULT NULL ,
 `IBAN` varchar( 255  )  DEFAULT NULL ,
 `Web` varchar( 255  )  NOT  NULL ,
 PRIMARY  KEY (  `AccountPlanID`  ) ,
 KEY  `Active` (  `Active`  )  ) ENGINE  =  MyISAM  DEFAULT CHARSET  = latin1;

INSERT INTO `accountplantemplate` (`AccountPlanID`, `AccountName`, `FirstName`, `LastName`, `VatID`, `Report`, `Budget`, `TS`, `InsertedDateTime`, `InsertedByPersonID`, `ValidFrom`, `ValidTo`, `debittext`, `credittext`, `Currency`, `Description`, `EnableReskontro`, `EnableQuantity`, `EnableDepartment`, `EnableProject`, `EnableReport1`, `EnableReport2`, `EnableReport3`, `EnableReport4`, `EnableReport5`, `EnableReport6`, `EnableReport7`, `EnableReport8`, `EnableReport9`, `EnableReport10`, `EnableReportShort`, `EnableBudgetResult`, `EnableBudgetLikviditet`, `Report1Line`, `Report2Line`, `Report3Line`, `Report4Line`, `Report5Line`, `Report6Line`, `Report7Line`, `Report8Line`, `Report9Line`, `Report10Line`, `ReportShort`, `EnableVATOverride`, `EnablePostPost`, `ReskontroFromAccount`, `ReskontroToAccount`, `EnableZeroYearly`, `Reskontro`, `EnableVAT`, `Address`, `ZipCode`, `Email`, `DomesticBankAccount`, `AbroadBankAccount`, `EnableSalary`, `SocialSecurityNumber`, `Municipality`, `EmployedFromDate`, `EmployedToDate`, `SalaryDue`, `EnableCredit`, `CreditDays`, `EnableAutogiro`, `EnableNettbank`, `DebitColor`, `CreditColor`, `Active`, `EnableCurrency`, `CustomerNumber`, `EnableMotkontoBalanse`, `MotkontoBalanse1`, `MotkontoBalanse2`, `MotkontoBalanse3`, `MotkontoResultat1`, `MotkontoResultat2`, `MotkontoResultat3`, `EnableMotkontoResultat`, `LastUsedTime`, `City`, `EnablePersonalUsage`, `EnableMoneyFlow`, `EnableSaldo`, `NorwegianStandardText`, `OrgNumber`, `VatNumber`, `SocietyNumber`, `KommuneID`, `WorkStart`, `WorkStop`, `EnableNorwegianStandard`, `PersonID`, `ProjectID`, `DepartmentID`, `TabellTrekk`, `ProsentTrekk`, `Phone`, `IPoBox`, `IPoBoxCity`, `Mobile`, `EnableInvoicePoBox`, `EnableInvoiceAddress`, `IPoBoxZipCode`, `BirthDate`, `WorkPercent`, `EnableSalaryPayment`, `Report1LinePage`, `Report2LinePage`, `Report3LinePage`, `Report4LinePage`, `Report5LinePage`, `Report6LinePage`, `Report7LinePage`, `Report8LinePage`, `Report9LinePage`, `Report10LinePage`, `IPoBoxZipCodeCity`, `Report66Line`, `Report0002Line`, `Report1224Line`, `Report2224Line`, `Report1028Line`, `Report1125Line`, `Report1217Line`, `Report1122Line`, `Report1052Line`, `Report1223Line`, `Report1219Line`, `Report1061Line`, `Report1239Line`, `Report1215Line`, `Report1221Line`, `Report1037Line`, `Report1025Line`, `Report1231Line`, `Report1022Line`, `Report1086Line`, `EnableReport1224`, `EnableReport2224`, `InvoiceCommentCustomerPosition`, `ReskontroAccountPlanType`, `AccountPlanType`, `UpdatedByPersonID`, `AccountLineFreeTextMatch`, `CountryCode`, `isAccountCustomer`, `isAccountSupplier`, `isAccountResult`, `isAccountBalance`, `isAccountEmployee`, `IBAN`, `Web`) VALUES
(1, '', '', '', 0, NULL, NULL, '2012-04-11 12:21:23', NULL, NULL, NULL, NULL, 'Betale', 'Lønn', '', '', 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', NULL, 0, 1, NULL, NULL, NULL, NULL, 0, '', '', '', '', '', NULL, NULL, NULL, NULL, NULL, NULL, 1, 6, 0, 0, 'debitblue', 'creditred', 1, 0, '', 0, 0, 0, 0, 0, 0, 0, 0, '2008-08-10 21:22:34', '', NULL, 1, 0, NULL, '', NULL, '', 0, '0000-00-00', '0000-00-00', NULL, NULL, 0, 0, '', '', '', '', '', '', 0, 0, '', '0000-00-00 00:00:00', '0.00', NULL, '', '', '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'bottom', NULL, 'employee', 2, NULL, 'NO', NULL, NULL, NULL, NULL, 1, NULL, ''),
(2, '', NULL, NULL, 0, NULL, NULL, '2012-04-11 08:52:45', NULL, NULL, NULL, NULL, 'Utgift', 'Inntekt', '', '', 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 300, 0, 0, 0, 0, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 'debitblue', 'creditred', 0, 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, '2012-03-23 13:18:54', NULL, 0, 0, 0, '', NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', NULL, NULL, NULL, '3000', '3000', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 1, 'bottom', '', 'result', 2, '', '', NULL, NULL, 1, NULL, NULL, NULL, ''),
(3, '', NULL, NULL, 0, NULL, NULL, '2012-04-11 12:21:37', NULL, NULL, NULL, NULL, 'Kjøp', 'Avgang', '', '', 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 0, 0, 0, 0, 0, NULL, NULL, 0, '', '0', '', '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'debitblue', 'creditred', 1, 0, '0', 0, 0, 0, 0, 0, 0, 0, 0, '2005-03-22 21:18:12', NULL, 0, 0, 0, '', NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', NULL, NULL, NULL, '1000', '1000', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 1, 'bottom', '', 'balance', 2, '', '', NULL, NULL, NULL, 1, NULL, NULL, ''),
(4, '', NULL, NULL, 0, NULL, NULL, '2012-04-11 12:23:06', NULL, NULL, NULL, NULL, 'Salg', 'Betaling', '', '', 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', NULL, 0, 0, NULL, NULL, NULL, NULL, 0, '', '', '', '', '', NULL, NULL, NULL, NULL, NULL, NULL, 1, 14, 0, 0, 'debitblue', 'creditred', 1, 0, '', 0, 0, 0, 0, 0, 0, 0, 0, '2012-03-23 13:18:09', '', 0, 0, 0, '', '', '', '', 0, '0000-00-00', '0000-00-00', 0, NULL, 0, 0, '', '', '', '', '', '', 0, 0, '', '0000-00-00 00:00:00', '0.00', 0, '', '', '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'bottom', '', 'customer', 2, '', '', 1, NULL, NULL, NULL, NULL, '', ''),
(5, '', NULL, NULL, 0, NULL, NULL, '2012-04-11 12:21:59', NULL, NULL, NULL, NULL, 'Betale', 'Kjøp', '', '', 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, NULL, 0, 0, '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', NULL, 0, 0, NULL, NULL, NULL, NULL, 0, '', '', '', '', '', NULL, NULL, NULL, NULL, NULL, NULL, 1, 10, 0, 0, 'debitblue', 'creditred', 1, 0, '', 0, 0, 0, 0, 0, 0, 0, 0, NULL, '', 0, 0, 0, '', '', '', '', 0, '0000-00-00', '0000-00-00', 0, NULL, 0, 0, '', '', '', '', '', '', 0, 0, '', '0000-00-00 00:00:00', '0.00', 0, '', '', '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'bottom', '', 'supplier', 2, '', '', NULL, 1, NULL, NULL, NULL, '', '');
