CREATE TABLE IF NOT EXISTS altinnlog (
  AltinnLogID INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Type VARCHAR(50) DEFAULT "ERROR",
  Class VARCHAR(255) NOT NULL DEFAULT "",
  Message TEXT,
  PersonID int(11),
  TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  AltinnReference int(11)
)
