ALTER TABLE accountline
CHANGE CarID CarID INT( 11 ) NULL DEFAULT NULL,
CHANGE ProjectID ProjectID INT( 11 ) NULL DEFAULT NULL;

ALTER TABLE accountplan
CHANGE ProjectID ProjectID INT( 11 ) NULL DEFAULT NULL,
CHANGE CarID CarID INT( 11 ) NULL DEFAULT NULL;

ALTER TABLE accountplantemplate
CHANGE ProjectID ProjectID INT( 11 ) NULL DEFAULT NULL,
CHANGE DepartmentID DepartmentID INT( 11 ) NULL DEFAULT NULL,
ADD CarID INT( 11 ) NULL DEFAULT NULL,
ADD EnableCar SMALLINT ( 6 ) NULL DEFAULT NULL;

ALTER TABLE allowancecharge
CHANGE ProjectID ProjectID INT( 11 ) NULL DEFAULT NULL,
CHANGE DepartmentID DepartmentID INT( 11 ) NULL DEFAULT NULL;

ALTER TABLE invoicein
CHANGE Project ProjectID INT( 11 ) NULL DEFAULT NULL,
CHANGE Department DepartmentID INT( 11 ) NULL DEFAULT NULL;

ALTER TABLE invoiceinline
CHANGE ProjectID ProjectID INT( 11 ) NULL DEFAULT NULL,
CHANGE DepartmentID DepartmentID INT( 11 ) NULL DEFAULT NULL,
CHANGE CarID CarID INT( 11 ) NULL DEFAULT NULL;

ALTER TABLE invoiceout
CHANGE ProjectID ProjectID INT( 11 ) NULL DEFAULT NULL,
CHANGE DepartmentID DepartmentID INT( 11 ) NULL DEFAULT NULL;

ALTER TABLE recurringout
CHANGE ProjectID ProjectID INT( 11 ) NULL DEFAULT NULL;

ALTER TABLE voucher
CHANGE DepartmentID DepartmentID INT( 11 ) NULL DEFAULT NULL,
CHANGE ProjectID ProjectID INT( 11 ) NULL DEFAULT NULL,
CHANGE CarID CarID INT( 11 ) NULL DEFAULT NULL;

ALTER TABLE salaryline
CHANGE CarID CarID INT( 11 ) NULL DEFAULT NULL;

ALTER TABLE salaryconfline
CHANGE CarID CarID INT( 11 ) NULL DEFAULT NULL;
